// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzuUMlXJyivjdYtkTNv6ujzp_abn4A1rQ',
    appId: '1:231774430356:android:c547cbffb078b4b7aac081',
    messagingSenderId: '231774430356',
    projectId: 'bike-theft-prevention-app',
    databaseURL: 'https://bike-theft-prevention-app-default-rtdb.firebaseio.com',
    storageBucket: 'bike-theft-prevention-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaalq3nvvPAha4lG8BjJLZ7D09fW_D_gI',
    appId: '1:231774430356:ios:9b3984700b0298b3aac081',
    messagingSenderId: '231774430356',
    projectId: 'bike-theft-prevention-app',
    databaseURL: 'https://bike-theft-prevention-app-default-rtdb.firebaseio.com',
    storageBucket: 'bike-theft-prevention-app.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );
}
